language: node_js
sudo: required

services:
  - docker

before_install:
  - docker pull angular/ngcontainer
  - docker run angular/ngcontainer
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
