language: node_js
sudo: required

services:
  - docker pull angular/ngcontainer
  - docker run angular/ngcontainer

before_install:
  - docker
node_js:
  - "6"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn test
