/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
/** @const */
var goog = {};

/**
 * @param {string} name
 * @return {void}
 */
goog.provide = function(name) {};

/**
 * @param {string} name
 * @return {string}
 */
goog.require = function(name) {};

/**
 * @param {!Object} me
 * @param {?=} opt_methodName
 * @param {...?} var_args
 * @return {?}
 */
goog.base = function(me, opt_methodName, var_args) {};
/** @const */
goog.dom = {};
/**
 * @constructor
 * @struct
 */
goog.dom.DomHelper = function() {};
/** @const */
goog.ui = {};

/**
 * @constructor
 * @struct
 * @param {(undefined|!goog.dom.DomHelper)=} opt_domHelper
 */
goog.ui.Component = function(opt_domHelper) {};

/**
 * @param {!Element} $element
 * @return {?}
 */
goog.ui.Component.prototype.decorateInternal = function($element) {};

/**
 * @return {?}
 */
goog.ui.Component.prototype.enterDocument = function() {};

/**
 * @return {?}
 */
goog.ui.Component.prototype.exitDocument = function() {};

/**
 * @return {?}
 */
goog.ui.Component.prototype.disposeInternal = function() {};
/** @const */
var wap = {};
/** @const */
wap.core = {};
/** @const */
wap.core.app = {};
/**
 * @constructor
 * @struct
 */
wap.core.app.View = function() {};

/**
 * @return {?}
 */
wap.core.app.View.getInstance = function() {};

/**
 * @param {string} name
 * @param {?} vo
 * @return {?}
 */
wap.core.app.View.registerComponent = function(name, vo) {};
